%% start of file `template.tex'.
%% Copyright 2006-2013 Xavier Danaux (xdanaux@gmail.com).
%
% This work may be distributed and/or modified under the
% conditions of the LaTeX Project Public License version 1.3c,
% available at http://www.latex-project.org/lppl/.


\documentclass[11pt,letterpaper,sans,colorlinks,linkcolor=true]{moderncv}        % possible options include font size ('10pt', '11pt' and '12pt'), paper size ('a4paper', 'letterpaper', 'a5paper', 'legalpaper', 'executivepaper' and 'landscape') and font family ('sans' and 'roman')

% moderncv themes
\moderncvstyle[shortrules]{banking}
%\moderncvstyle{banking}                             % style options are 'casual' (default), 'classic', 'oldstyle' and 'banking'
%\moderncvcolor{purple}                               % color options 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'
\moderncvcolor{blue}
%\renewcommand{\familydefault}{\sfdefault}         % to set the default font; use '\sfdefault' for the default sans serif font, '\rmdefault' for the default roman one, or any tex font name
\nopagenumbers{}                                  % uncomment to suppress automatic page numbering for CVs longer than one page

% character encoding
\usepackage[utf8]{inputenc}                       % if you are not using xelatex ou lualatex, replace by the encoding you are using
%\usepackage{CJKutf8}                              % if you need to use CJK to typeset your resume in Chinese, Japanese or Korean

% adjust the page margins
\usepackage[scale=0.75]{geometry}
%\setlength{\hintscolumnwidth}{3cm}                % if you want to change the width of the column with the dates
%\setlength{\makecvtitlenamewidth}{10cm}           % for the 'classic' style, if you want to force the width allocated to your name and avoid line breaks. be careful though, the length is normally calculated to avoid any overlap with your personal info; use this at your own typographical risks...


% personal data
\name{Leonardo}{Collado-Torres}
%\title{Resumé title}                               % optional, remove / comment the line if not wanted
\address{855 N. Wolfe Street, Suite 300}{21205}{United States}% optional, remove / comment the line if not wanted; the "postcode city" and and "country" arguments can be omitted or provided empty
%\phone[mobile]{+1~(234)~567~890}                   % optional, remove / comment the line if not wanted
\phone[fixed]{+1~(410)~955~1000}                    % optional, remove / comment the line if not wanted
%\phone[fax]{+3~(456)~789~012}                      % optional, remove / comment the line if not wanted
\email{leo.collado@libd.org}                               % optional, remove / comment the line if not wanted
\homepage{http://lcolladotor.github.io/}                         % optional, remove / comment the line if not wanted
%\extrainfo{Blog: http://lcolladotor.github.io/}                 % optional, remove / comment the line if not wanted
\social[twitter]{fellgernon}
\social[github]{lcolladotor}
%\photo[64pt][0.4pt]{picture}                       % optional, remove / comment the line if not wanted; '64pt' is the height the picture must be resized to, 0.4pt is the thickness of the frame around it (put it to 0pt for no frame) and 'picture' is the name of the picture file
%\quote{Some quote}                                 % optional, remove / comment the line if not wanted

% to show numerical labels in the bibliography (default is to show no labels); only useful if you make citations in your resume
%\makeatletter
%\renewcommand*{\bibliographyitemlabel}{\@biblabel{\arabic{enumiv}}}
%\makeatother
%\renewcommand*{\bibliographyitemlabel}{[\arabic{enumiv}]}% CONSIDER REPLACING THE ABOVE BY THIS

% bibliography with mutiple entries
%\usepackage{multibib}
%\newcites{book,misc}{{Books},{Others}}
%----------------------------------------------------------------------------------
%            content
%----------------------------------------------------------------------------------

\topmargin=0.05in
\textheight=8.15in
\textwidth=5.6in
\oddsidemargin=0.7in
\raggedbottom
\newdimen \jot \jot=5mm
\brokenpenalty=10000

\begin{document}

%% https://tex.stackexchange.com/questions/275848/changing-moderncv-link-color-of-href
%% https://en.wikibooks.org/wiki/LaTeX/Colors
\definecolor{links}{HTML}{FF7F00}
\hypersetup{urlcolor=links}

%\pagestyle{plain}
%\pagenumbering{arabic}
%\setcounter{page}{118}
%\cfoot{\thepage}

%\begin{CJK*}{UTF8}{gbsn}                          % to typeset your resume in Chinese using CJK
%-----       resume       ---------------------------------------------------------
\makecvtitle

<<setup, echo = FALSE>>=
library(knitr)
@

<<'getStats', echo=FALSE>>=
getDownloads <- function(pkg, data = FALSE) {
    if(data) {
        info <- read.table(paste0('https://bioconductor.org/packages/stats/data-experiment/',
        pkg, '/', pkg, '_stats.tab'), header = TRUE)
    } else {
        info <- read.table(paste0('https://bioconductor.org/packages/stats/bioc/',
        pkg, '/', pkg, '_stats.tab'), header = TRUE)
    }
    sum(info$Nb_of_downloads[info$Month == 'all'])
}
@


\input{education.tex}
\input{honors.tex}
\input{experience.tex}
\input{pubList.tex}
\input{profiles.tex}
\input{service.tex}
\input{presentations.tex}
\input{courses.tex}
\section{Software}
\subsection{Bioconductor -- main author}
\cvitem{2016}{\httplink[recount]{bioconductor.org/packages/recount}: Explore and download data from the recount project -- \Sexpr{getDownloads('recount')} downloads.}
\cvitem{2014}{\httplink[derfinder]{bioconductor.org/packages/derfinder}: Annotation-agnostic differential expression analysis of RNA-seq data at base-pair resolution via the DER Finder approach -- \Sexpr{getDownloads('derfinder')} downloads.}
\cvitem{2014}{\httplink[derfinderPlot]{bioconductor.org/packages/derfinderPlot}: plotting functions for derfinder results -- \Sexpr{getDownloads('derfinderPlot')} downloads.}
\cvitem{2014}{\httplink[regionReport]{bioconductor.org/packages/regionReport}: Generate HTML or PDF reports for a set of genomic regions or DESeq2/edgeR results -- \Sexpr{getDownloads('regionReport')} downloads.}
\cvitem{2014}{\httplink[derfinderHelper]{bioconductor.org/packages/derfinderHelper}: helper functions for derfinder package -- \Sexpr{getDownloads('derfinderHelper')} downloads.}
\cvitem{2014}{\httplink[derfinderData]{bioconductor.org/packages/derfinderData}: data for derfinder examples -- \Sexpr{getDownloads('derfinderData', TRUE)} downloads.}
\input{software.tex}
\input{computer.tex}
\input{teaching.tex}
\input{mentoring.tex}
\input{other.tex}
\input{languages.tex}

\end{document}


%% end of file `template.tex'.


